packages:
  - "."

allowBuilds:
  esbuild: set this to true or false

pnpm:
  onlyBuiltDependencies:
    - esbuild
  autoInstallPeers: true
  strictPeerDependencies: false
  packageImportMethod: clone-or-copy
